use `disaster_management`;

insert into `donation_tracker`
values
(2, 'Mr. X', 'x@gmail.com', '01500000000', 1500, '2024-09-16 14:30:00.065000'),
(3, 'Mr. X', 'x@gmail.com', '01500000000', 1000, '2024-09-16 15:30:00.065000'),
(4, 'Mr. Y', 'y@gmail.com', '01700000000', 2500, '2024-09-17 14:30:00.065000'),
(5, 'Mr. X', 'x@gmail.com', '01500000000', 60, '2024-09-17 15:30:00.065000'),
(6, 'Mr. Z', 'z@gmail.com', '01800000000', 1000, '2024-09-17 16:30:00.065000'),
(7, 'Mr. Y', 'y@gmail.com', '01700000000', 2500, '2024-09-18 14:30:00.065000'),
(8, 'Mr. Y', 'y@gmail.com', '01700000000', 3500, '2024-09-19 14:30:00.065000'),
(9, 'Mr. A', 'a@gmail.com', '01510000001', 2000, '2024-09-20 16:30:00.065000'),
(10, 'Mr. B', 'b@gmail.com', '01510000002', 2500, '2024-09-20 17:30:00.065000'),
(11, 'Mr. C', 'c@gmail.com', '01510000003', 3000, '2024-09-21 18:30:00.065000'),
(12, 'Mr. D', 'd@gmail.com', '01510000004', 3500, '2024-09-21 19:30:00.065000'),
(13, 'Mr. E', 'e@gmail.com', '01510000005', 4000, '2024-09-21 20:30:00.065000'),
(14, 'Mr. F', 'f@gmail.com', '01510000006', 4500, '2024-09-21 21:30:00.065000'),
(15, 'Mr. G', 'g@gmail.com', '01510000007', 5000, '2024-09-22 22:30:00.065000'),
(16, 'Mr. H', 'h@gmail.com', '01510000008', 5500, '2024-09-22 23:30:00.065000'),
(17, 'Mr. I', 'i@gmail.com', '01510000009', 6000, '2024-09-23 00:30:00.065000'),
(18, 'Mr. J', 'j@gmail.com', '01510000010', 6500, '2024-09-23 01:30:00.065000'),
(19, 'Mr. K', 'k@gmail.com', '01510000011', 7000, '2024-09-23 02:30:00.065000'),
(20, 'Mr. L', 'l@gmail.com', '01510000012', 7500, '2024-09-24 03:30:00.065000');


insert into `new_crisis`
values
(1, "New Crisis (Serious).jpg", "Massive Flood in Sylhet", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Sylhet, Bangladesh", "2024-09-19 03:30:00.065000", "serious", "Volunteers and relief goods"),
(2, "New Crisis (Very Serious).jpg", "Cyclone in Chittagong", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Chittagong, Bangladesh", "2024-09-20 06:00:00.065000", "very_serious", "Evacuations and shelter arrangements"),
(3, "New Crisis (Serious).jpg", "Earthquake Hits Sylhet", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Sylhet, Bangladesh", "2024-09-20 07:00:00.065000", "serious", "Rescue operations and medical aid"),
(4, "New Crisis (Normal).jpg", "Drought in Rajshahi", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Rajshahi, Bangladesh", "2024-09-20 08:00:00.065000", "normal", "Water scarcity and crop failure"),
(5, "New Crisis (Serious).jpg", "River Erosion in Kurigram", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Kurigram, Bangladesh", "2024-09-20 09:00:00.065000", "serious", "Displacement of families"),
(6, "New Crisis (Serious).jpg", "Landslide in Chittagong Hill Tracts", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Chittagong, Bangladesh", "2024-09-20 10:00:00.065000", "serious", "Rescue operations and recovery"),
(7, "New Crisis (Serious).jpg", "Tsunami Warning for Coastal Areas", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Cox's Bazar, Bangladesh", "2024-09-20 11:00:00.065000", "serious", "Evacuation underway"),
(8, "New Crisis (Normal).jpg", "Heatwave Hits Dhaka", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Dhaka, Bangladesh", "2024-09-20 12:00:00.065000", "normal", "Health concerns due to heatstroke"),
(9, "New Crisis (Normal).jpg", "Salinity Intrusion in Khulna", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Khulna, Bangladesh", "2024-09-20 13:00:00.065000", "normal", "Agricultural lands affected"),
(10, "New Crisis (Normal).jpg", "Waterlogging in Barishal", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Barishal, Bangladesh", "2024-09-20 14:00:00.065000", "normal", "Disruption of daily life and transport"),
(11, "New Crisis (Very Serious).jpg", "Air Pollution in Dhaka", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ullamcorper velit id urna dapibus, at convallis sem elementum. Suspendisse potenti. Aenean cursus eros ut erat interdum, sit amet bibendum ligula interdum. Integer vel nunc in ligula faucibus scelerisque. Cras tincidunt, justo ac dictum tristique, risus libero porttitor nulla, ac congue dui ex vel metus. Nulla facilisi. Duis laoreet convallis urna at efficitur. Mauris malesuada arcu et elit convallis, nec faucibus elit vehicula. Quisque id sapien ut justo tincidunt lacinia. Donec ac velit ut libero interdum eleifend. Proin tincidunt magna vitae ex eleifend auctor. Praesent eget tincidunt velit. Phasellus ut dolor vitae erat suscipit volutpat. Nulla aliquam arcu id sapien volutpat, non consectetur arcu hendrerit. Integer convallis est ut lorem venenatis malesuada. Curabitur varius, elit non congue scelerisque, nisl augue eleifend quam, vitae vulputate dui lacus ac justo.
", "Dhaka, Bangladesh", "2024-09-20 15:00:00.065000", "very_serious", "Health risks and respiratory issues");



insert into `all_crisis`
values
(1, "Active Crisis (Very Serious).jpg", "Price Hiking Leads Hunger", "lorem", "Dhaka, Bangladesh", "2024-09-19 03:30:00.065000", "very_serious", "Need volunteers to break the syndicate", "active"),
(2, "Inactive Crisis (Serious).jpg", "Unexpected Flood in Cumilla", "lorem", "Cumila, Bangladesh", "2024-09-20 04:30:00.065000", "serious", "Need volunteers to provide relief goods", "inactive"),
(3, "Active Crisis (Serious).jpg", "Cyclone Hits Coastal Area", "lorem", "Cox's Bazar, Bangladesh", "2024-09-21 05:30:00.065000", "serious", "Need volunteers for rescue operations", "active"),
(4, "Inactive Crisis (Very Serious).jpg", "Earthquake Shakes Sylhet", "lorem", "Sylhet, Bangladesh", "2024-09-22 06:30:00.065000", "very_serious", "Need volunteers for medical assistance", "inactive"),
(5, "Active Crisis (Serious).jpg", "Drought in Rajshahi", "lorem", "Rajshahi, Bangladesh", "2024-09-23 07:30:00.065000", "serious", "Need irrigation support for farmers", "active"),
(6, "Inactive Crisis (Normal).jpg", "Riverbank Erosion in Kurigram", "lorem", "Kurigram, Bangladesh", "2024-09-24 08:30:00.065000", "normal", "Need temporary shelters for displaced people", "inactive"),
(7, "Active Crisis (Normal).jpg", "Heatwave Grips Dhaka", "lorem", "Dhaka, Bangladesh", "2024-09-25 09:30:00.065000", "normal", "Need volunteers to distribute water", "active"),
(8, "Inactive Crisis (Serious).jpg", "Waterlogging in Khulna", "lorem", "Khulna, Bangladesh", "2024-09-26 10:30:00.065000", "serious", "Need drainage system improvements", "inactive"),
(9, "Active Crisis (Very Serious).jpg", "Salinity Intrusion in Barisal", "lorem", "Barisal, Bangladesh", "2024-09-27 11:30:00.065000", "very_serious", "Need water purification facilities", "active"),
(10, "Inactive Crisis (Very Serious).jpg", "Tsunami Threat in Cox's Bazar", "lorem", "Cox's Bazar, Bangladesh", "2024-09-28 12:30:00.065000", "very_serious", "Need evacuation plans", "inactive"),
(11, "Active Crisis (Serious).jpg", "Air Pollution in Dhaka", "lorem", "Dhaka, Bangladesh", "2024-09-29 13:30:00.065000", "serious", "Need air quality improvement measures", "active"),
(12, "Inactive Crisis (Serious).jpg", "Flood in Bogra", "lorem", "Bogra, Bangladesh", "2024-09-30 14:30:00.065000", "serious", "Need relief and rehabilitation efforts", "inactive"),
(13, "Active Crisis (Normal).jpg", "Landslide in Chittagong Hills", "lorem", "Chittagong, Bangladesh", "2024-10-01 15:30:00.065000", "normal", "Need emergency response teams", "active"),
(14, "Inactive Crisis (Normal).jpg", "Tornado in Mymensingh", "lorem", "Mymensingh, Bangladesh", "2024-10-02 16:30:00.065000", "normal", "Need medical aid and support", "inactive"),
(15, "Active Crisis (Serious).jpg", "Flood in Jamalpur", "lorem", "Jamalpur, Bangladesh", "2024-10-03 17:30:00.065000", "serious", "Need volunteers for distribution of relief", "active"),
(16, "Inactive Crisis (Very Serious).jpg", "Severe Storm in Patuakhali", "lorem", "Patuakhali, Bangladesh", "2024-10-04 18:30:00.065000", "very_serious", "Need immediate emergency support", "inactive");
